apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: zeppaaks.azurecr.io/azure-vote-front
    newTag: b9ac5eaa7fef9d4ebec5202c42d49cceae6306f3
  - name: zeppaaks.azurecr.io/azure-vote-back
    newTag: b9ac5eaa7fef9d4ebec5202c42d49cceae6306f3
resources:
  - manifests.yaml