apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: zeppaaks/.azurecr.io//azure-vote-front
    newTag: 3d68dc9f89190777ace9b4a5ead22996b86a40eb
  - name: zeppaaks/.azurecr.io//azure-vote-back
    newTag: 3d68dc9f89190777ace9b4a5ead22996b86a40eb
resources:
  - manifests.yaml