apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: zeppaaks/.azurecr.io//azure-vote-front
    newTag: 57a43031cd89c46b76037b12d8567241f327d3b3
  - name: zeppaaks/.azurecr.io//azure-vote-back
    newTag: 57a43031cd89c46b76037b12d8567241f327d3b3
resources:
  - manifests.yaml