apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: zeppaaks.azurecr.io/azure-vote-front
    newTag: fd71d26ad3f0f9cd9dd58b2e7f11fb5b9d7a79bb
  - name: zeppaaks.azurecr.io/azure-vote-back
    newTag: fd71d26ad3f0f9cd9dd58b2e7f11fb5b9d7a79bb
resources:
  - manifests.yaml