apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: zeppaaks-aua5grb9a0g3f3b5.azurecr.io/azure-vote-front
    newTag: 6a1034a0a924619ca3d37815ade2ac418d554e19
  - name: zeppaaks-aua5grb9a0g3f3b5.azurecr.io/azure-vote-back
    newTag: 6a1034a0a924619ca3d37815ade2ac418d554e19
resources:
  - manifests.yaml