apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: zeppaaks-aua5grb9a0g3f3b5.azurecr.io/azure-vote-front
    newTag: 7a360c71fb427b79a80ad1912eb84fd023641c1b
  - name: zeppaaks-aua5grb9a0g3f3b5.azurecr.io/azure-vote-back
    newTag: 7a360c71fb427b79a80ad1912eb84fd023641c1b
resources:
  - manifests.yaml